version: '3.1'

# sudo docker-compose --env-file ../.env up -d

services:

  db:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: $PASSWORD
      POSTGRES_USER: $USERNAME

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080